version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Disable rebasing for npm pull requests
    rebase-strategy: "auto"
    labels:
      - "automerge"
      - "dependencies"
